---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azdiskschedulerextender-config
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: azdiskschedulerextender
    algorithmSource:
      policy:
        configMap:
          namespace: kube-system
          name: azdiskschedulerextender-policy
    leaderElection:
      leaderElect: true
      lockObjectName: azdiskschedulerextender
      lockObjectNamespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azdiskschedulerextender-policy
  namespace: kube-system
data:
 policy.cfg : |
  {
    "kind" : "Policy",
    "apiVersion" : "v1",
    "predicates" : [
      {"name" : "PodFitsHostPorts"},
      {"name" : "PodFitsResources"},
      {"name" : "NoDiskConflict"},
      {"name" : "MatchNodeSelector"},
      {"name" : "HostName"}
    ],
    "priorities" : [
      {"name" : "LeastRequestedPriority", "weight" : 1},
      {"name" : "BalancedResourceAllocation", "weight" : 1},
      {"name" : "ServiceSpreadingPriority", "weight" : 1},
      {"name" : "EqualPriority", "weight" : 1}
    ],
    "extenders" : [{
      "urlPrefix": "http://localhost:8080/azdiskschedulerextender",
      "filterVerb": "filter",
      "prioritizeVerb": "prioritize",
      "weight": 1,
      "enableHttps": false,
      "nodeCacheCapable": false
    }],
    "hardPodAffinitySymmetricWeight" : 10
  }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdiskschedulerextender
  namespace: kube-system
  labels:
    app: azdiskschedulerextender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azdiskschedulerextender
  template:
    metadata:
      labels:
        app: azdiskschedulerextender
    spec:
      serviceAccountName: azdiskschedulerextender
      volumes:
      - name: azdiskschedulerextender-config
        configMap:
          name: azdiskschedulerextender-config
      containers:
      - name: azdiskscheduler-ctr
        image: gcr.io/google_containers/hyperkube:v1.16.3
        imagePullPolicy: IfNotPresent
        args:
        - kube-scheduler
        - --config=/azdiskschedulerextender/config.yaml
        - --v=5
        volumeMounts:
        - name: azdiskschedulerextender-config
          mountPath: /azdiskschedulerextender
      - name: azdiskschedulerextender-ctr
        image: docker.io/landreasyan/azdiskschedulerextender-csi:latest
        imagePullPolicy: Always
        args:
        - "--port=8080"
        - "--metrics-address=0.0.0.0:29604"
        - "--v=5"
        livenessProbe:
          httpGet:
            path: /ping
            port: extender-port
          failureThreshold: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: extender-port
          failureThreshold: 3
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /ping
            port: extender-port
          failureThreshold: 20
          periodSeconds: 3
        ports:
          - name: extender-port
            containerPort: 8080
            hostPort: 8080
          - name: metrics-port
            containerPort: 29604
            protocol: TCP